### ISSUE TITLE
CODEXUploader not working when the source data is on a network drive

### ISSUE THREAD

**Issue by nsamusik** [nolanlab/CODEX#30]
For some reason, when the source data is on the network-mapped drive, the Uploader isn't working: it is able to open the folder and parse the folder contents to populate the ExperimentView, but the 'Start' button doesn't do anything and there are no exceptions shown in the console.  At the same time, when Driffta is started manually from a BAT file, it works

**Comment by vishal266** [comment]
Looking at it right now.

**Comment by vishal266** [comment]
Hi all,

The network drive issue looks like it happens because of access denied error: 
Caused by: java.io.FileNotFoundException: \\Win-j530bs39qlf\e\180223_FFPE_tonsil_organoid_Ron\Experiment.json (Access is denied)
at java.io.FileOutputStream.open0(Native Method)
 
Thats why nothing happens when you try to click on start.

I will print this message out on the textArea. 

Thanks,
Vishal

**Comment by vishal266** [comment]
Fixed this issue. available in latest commit. But not released yet.
